Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "geerlingguy/centos7"
    web.vm.hostname = "web"

    web.vm.network "private_network", ip: "192.168.3.10"

    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    web.vm.provision "shell", path:"setup.sh"
  end

end
